### ISSUE TITLE
drycc.yaml support

### ISSUE THREAD

**Issue by duanhongyi** [drycc/workflow#48]
# setup
* 仅在第一次提交的时候运行
* 一般为初始化资源和环境变量

# build
* buildpack和container是互斥的
* config为build镜像时候传递的变量(--build-arg)

# release
* 每次部署前需要执行的语句
* image可选，buildpack情况下无image字段
* image可以是内部build名称，也可以是外部的image镜像

# run
* 可以是一个字典类型，也可以是字符串，具体看样例
* 字符串类型默认同build一一对应，如果无 build
* buildpack类型无image字段
* image可以是内部build名称，也可以是外部的image镜像

```
setup:
  resources:
  - name: postgres
    plan: postgresql-cluster:standard-50
  config:
    S3_BUCKET: my-example-bucket
build:
  docker:
    web: Dockerfile
    worker: worker/Dockerfile
  config:
    RAILS_ENV: development
    FOO: bar
release:
  command:
  - ./deployment-tasks.sh
  image: worker
run:
  web: bundle exec puma -C config/puma.rb
  worker: python myworker.py
  asset-syncer:
    command:
    - python asset-syncer.py
    image: worker
```
